--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/nhanaz-pm-pl/BlockDataRecorder
build-by-default: true
branches:
- master
projects:
  BlockDataRecorder:
    path: ""
    libs:
      - src: NhanAZ/BlockData/BlockData
        version: 0.0.4
      - src: NhanAZ/libBedrock/libBedrock
        version: 1.1.1
...
