---
name: BlockDataRecorder
version: 0.0.5
main: NhanAZ\BlockDataRecorder\Main
api: 5.0.0
website: https://github.com/NhanAZ
author: NhanAZ
description: The data of an item block will not be lost when the block is placed
...
