on:
  push:
jobs:
  build-phar:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
      - uses: SOF3/pharynx@v0.2
        id: pharynx
        with:
          pharynx-version: "0.3.0"
      - uses: actions/upload-artifact@v3
        with:
          name: BlockDataRecorder.phar
          path: ${{steps.pharynx.outputs.output-phar}}
      - uses: actions/upload-artifact@v3
        with:
          name: BlockDataRecorder
          path: ${{steps.pharynx.outputs.output-dir}}